services:
  ordersmicroservice.api:
    image: ordersmicroservice-api
    build:
      context: .
      dockerfile: OrdersMicroservice.API/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development,
     - MONGODB_HOST=localhost
     - MONGODB_PORT=27017
     - MONGODB_DATABASE=OrdersDatabase
     - UsersMicroserviceName=localhost
     - UsersMicroservicePort=5050
    ports:
     - "7000:8080"